credentials:
  usernames:
    pkmsumbersari:
      email: jsmith@gmail.com
      name: Puskesmas Sumbersari
      password: sumbersari123
      failed_login_attempts: 0
      logged_in: false

    pkmkaliwates:
      email: rbriggs@gmail.com
      name: Puskesmas Kaliwates
      password: kaliwates123
      failed_login_attempts: 0
      logged_in: false

cookie:
  expiry_days: 30
  key: some_cookie_key_123
  name: some_cookie_name

pre-authorized:
  emails:
    - melsby@gmail.com
