credentials:
  usernames:
    pkmsumbersari:
      email: jsmith@gmail.com
      failed_login_attempts: 3 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Puskesmas Sumbersari
      password: sumbersari123 # Will be hashed automatically
    pkmkaliwates:
      email: rbriggs@gmail.com
      failed_login_attempts: 3 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Puskesmas Kaliwates
      password: kaliwates123 # Will be hashed automatically
cookie:
  expiry_days: 999999999
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com
