credentials:
  usernames:
    pkmsumbersari:
      email: jsmith@gmail.com
      name: Puskesmas Sumbersari
      password: $2a$12$sz76J6aXyjRRbs4m3v.mZuFMl.bPQ7i/O8bTUUMPFYJZofp2sGsl.
      failed_login_attempts: 0
      logged_in: false

    pkmkaliwates:
      email: rbriggs@gmail.com
      name: Puskesmas Kaliwates
      password: $2a$12$D3TtlqEjDca2XnVn77VwOeZ9xoJHLINznj.eZ1XJCaGEimwT3YznS
      failed_login_attempts: 0
      logged_in: false

cookie:
  expiry_days: 30
  key: some_cookie_key_123
  name: some_cookie_name
